//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWinFormsApp.SampleService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SampleService.IStateMachineService")]
    public interface IStateMachineService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStateMachineService/GetInitialState", ReplyAction="http://tempuri.org/IStateMachineService/GetInitialStateResponse")]
        string GetInitialState();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStateMachineService/GetAvailableEvents", ReplyAction="http://tempuri.org/IStateMachineService/GetAvailableEventsResponse")]
        string[] GetAvailableEvents(string currentState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStateMachineService/GetNewState", ReplyAction="http://tempuri.org/IStateMachineService/GetNewStateResponse")]
        string GetNewState(string currentState, string triggeringEvent);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStateMachineServiceChannel : SampleWinFormsApp.SampleService.IStateMachineService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StateMachineServiceClient : System.ServiceModel.ClientBase<SampleWinFormsApp.SampleService.IStateMachineService>, SampleWinFormsApp.SampleService.IStateMachineService {
        
        public StateMachineServiceClient() {
        }
        
        public StateMachineServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StateMachineServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StateMachineServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StateMachineServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetInitialState() {
            return base.Channel.GetInitialState();
        }
        
        public string[] GetAvailableEvents(string currentState) {
            return base.Channel.GetAvailableEvents(currentState);
        }
        
        public string GetNewState(string currentState, string triggeringEvent) {
            return base.Channel.GetNewState(currentState, triggeringEvent);
        }
    }
}
